version: '3.8'
services:
  smarthouse:
    build: .
    entrypoint: ["python3", "/usr/src/smarthouse/server.py"]
    restart: unless-stopped
    volumes:
      - ./storage/:/usr/src/smarthouse/storage
    ports:
      - "8080:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"
    healthcheck:  # todo: this is dont work
      test: [ "CMD", "curl", "-f", "http://0.0.0.0:8080/health" ]
      interval: 30s
      timeout: 1s
      retries: 5
      start_period: 10s
#    depends_on:
#      - homeassistant

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "8811:8811"
    logging:
      driver: "json-file"
      options:
        max-size: "2048m"

#  homeassistant:
#    container_name: homeassistant
#    privileged: true
#    image: "ghcr.io/home-assistant/home-assistant:2023.7.2"
#    restart: unless-stopped
#    volumes:
#      - /home/ivan/homeassistant_config:/config
#      - /etc/localtime:/etc/localtime:ro
#    ports:
#      - "8123:8123"
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "2048m"

#  restarter:
#      image: docker
#      volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
#      command: ["/bin/sh", "-c", "while true; do sleep 1209600; docker restart smarthouse-smarthouse-1; done"]  # 2 weeks
#      restart: unless-stopped
