name: Deploy Ya
run-name: ${{ github.actor }} Deploy Ya

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

concurrency: deploy

jobs:
  build:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
    - name: Create SSH key
      run: |
        apk update -qq
        apk add -qq git
        'which ssh-agent || ( apk add -qq openssh-client )'
        eval $(ssh-agent -s)
        echo "$SSH_PRIVATE_KEY" | ssh-add -
        mkdir -p ~/.ssh
        '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
      env:
        SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

    - name: Deploy
      run: |
        ssh ivan@51.250.77.64 "cd /home/ivan/home && git fetch --all && git checkout $GITHUB_SHA && git pull --force && sudo docker compose -f docker-compose.yml up --build -d  && exit"
