name: Test and Deploy
run-name: ${{ github.actor }} Test and Linters

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

permissions:
  pull-requests: write

jobs:
  linters:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
      - name: Lint with black
        run: |
          black --check .
      - name: Lint with isort
        run: |
          isort --check .
      - name: Lint with mypy
        run: |
          mypy smarthouse example server.py lambda/lambda.py
      - name: Lint with flake8
        run: |
          flake8 smarthouse example server.py lambda/lambda.py

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements-dev.txt
          pip install coveralls
          cp "./tests/.env" "./.env"
      - name: Test with pytest
        run: |
          pytest -n 4 --cov smarthouse tests
          coverage report --include "smarthouse/*" --skip-empty --fail-under=30
          coverage xml --include "smarthouse/*" --skip-empty
          coveralls
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: [unit-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" >  ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 51.250.84.107 > ~/.ssh/known_hosts
          
          echo "---"
          echo "$SSH_HOST"
          echo "---"
          cat ~/.ssh/known_hosts
          echo "---"
          echo "$SSH_PRIVATE_KEY"
          echo "---"
          cat ~/.ssh/id_rsa
          echo "---"
        env:
          SSH_HOST: ${{secrets.SSH_HOST}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

      - name: Deploy
        run: |
          if [[ -v GITHUB_HEAD_REF ]]
          then
            ref=${GITHUB_HEAD_REF}
          else
            ref=${GITHUB_REF##*/}
          fi
          echo $ref

          ssh ivan@51.250.84.107 "cd /home/ivan/smarthouse && git fetch --all && git checkout "${ref}" && git pull --force && sudo docker compose -f docker-compose.yml up --build -d  && exit"
