name: Unit Tests
run-name: ${{ github.actor }} Unit Tests

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies and env
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/requirements-dev.txt
        cp "./tests/.env" "./.env"
    - name: Test with pytest
      run: |
        pytest -n 4 --cov src tests
        coverage report --include "src/lib/*" --skip-empty --fail-under=50
        coverage xml --include "src/lib/*" --skip-empty

    - name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: coverage.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '60 80'
    - name: Add Coverage PR Comment
      uses: marocchino/sticky-pull-request-comment@v2
      if: github.event_name == 'pull_request'
      with:
        recreate: true
        path: code-coverage-results.md
